### ISSUE TITLE
Dynamic redis autoscaling (dyn_auto_redis) not working

### ISSUE THREAD

**Issue by gskorokhod** [gskorokhod/dispel4py_autoscaling#1]
# Description
Can't run with dynamic redis autoscaling mapping, crashes with the following error message:

`(d4p-py37) mayday@localhost:~/Coding/Projects/dispel4py/repos/dispel4py_autoscaling> dispel4py dyn_auto_redis dispel4py.examples.graph_testing.pipeline_tes -i 10 -n 6 -thr 200
Failed to load graph from "dispel4py.examples.graph_testing.pipeline_tes":
No module "dispel4py.examples.graph_testing.pipeline_tes"
Error loading graph from file:
Traceback (most recent call last):
  File "/home/mayday/Applications/anaconda3/envs/d4p-py37/lib/python3.7/site-packages/dispel4py-1.4.0-py3.7.egg/dispel4py/utils.py", line 82, in load_graph
    return loadGraphFromFile(module_name, graph_source, attr)
  File "/home/mayday/Applications/anaconda3/envs/d4p-py37/lib/python3.7/site-packages/dispel4py-1.4.0-py3.7.egg/dispel4py/utils.py", line 46, in loadGraphFromFile
    module = util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
`

# System info

- Personal laptop
OS: OpenSuse Tumbleweed (Linux)
Python environment: conda (d4p-py37), Python 3.7, set up as described in readme

# TODO
- [ ] Attempt to reproduce on other system (lab machines)
- [ ] Examine the `loadGraphFromFile` method
- [ ] Find line that is causing the issue
- [ ] Come up with a fix
