### ISSUE TITLE
Could not test hybrid_redis

### ISSUE THREAD

**Issue by gskorokhod** [gskorokhod/dispel4py_autoscaling#2]
# Description

Could not test the hybrid_redis mapping as the file could not be found by dispel4py, even though the file clearly exists. 
Possible configuration issue?
(Dispel4py was set up using the provided setup script and no changes have been made)

```
(d4p-py37) mayday@localhost:~/Coding/Projects/dispel4py/repos/dispel4py_autoscaling> dispel4py hybrid_redis dispel4py.examples.graph_testing.grouping_alltoone_stateful.py -i 100 -n 10
Failed to load graph from "dispel4py.examples.graph_testing.grouping_alltoone_stateful.py":
No module "dispel4py.examples.graph_testing.grouping_alltoone_stateful.py"
No file "dispel4py.examples.graph_testing.grouping_alltoone_stateful.py"
```

# System
- Personal laptop
OS: OpenSuse Tumbleweed (Linux)
Python environment: Python 3.7 (conda d4p-py37)

# TODO
- [ ] Ask Rosa about how exactly the dispel4py binary is installed
- [ ] Ask / figure out how it looks for files
- [ ] Try to reproduce on lab machine
- [ ] Try other ways of running d4p
